#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 05_prepare_variant_table.sh
#
# Prepare the final variant table from the combined SnpEff
# annotations generated by 04_analyze_samples.sh.
#
# INPUT:
#   results/summary/all_variants.tsv
#
# OUTPUT:
#   results/summary/all_variants_annotated.tsv
#
# This reproduces the annotation parsing performed in the
# historical workflow, retaining selected SnpEff ANN fields.
# ============================================================


# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

INPUT="${REPO_ROOT}/results/summary/all_variants.tsv"
OUTPUT="${REPO_ROOT}/results/summary/all_variants_annotated.tsv"


# ------------------------------------------------------------
# Check input
# ------------------------------------------------------------

if [[ ! -s "${INPUT}" ]]; then
    echo "[ERROR] Input file not found or empty:"
    echo "        ${INPUT}" >&2
    exit 1
fi


echo "[INFO] Preparing final annotated variant table"
echo "[INFO] Input:"
echo "       ${INPUT}"


# ------------------------------------------------------------
# Parse SnpEff ANN field
#
# ANN fields:
#
#  1  Allele
#  2  Annotation
#  3  Impact
#  4  Gene name
#  5  Gene ID
#  6  Feature type
#  7  Feature ID
#  8  Transcript biotype
#  9  Rank / total
# 10  HGVS.c
# 11  HGVS.p
# 12  cDNA position / length
# 13  CDS position / length
# 14  Protein position / length
# 15  Distance to feature
# 16  Errors / warnings
#
# Historical workflow retained:
#   2, 3, 4, 11, 13, 14, 16
#
# If SnpEff reports several annotations separated by commas,
# the first annotation is retained. This reproduces the
# effective behaviour of the original parsing workflow.
# ------------------------------------------------------------

awk '
BEGIN {
    FS = OFS = "\t"

    print "segment",
          "position",
          "REF",
          "ALT",
          "QUAL",
          "sample",
          "DP",
          "AF",
          "annotation",
          "impact",
          "gene_name",
          "HGVS.p",
          "CDS_position",
          "protein_position",
          "warnings"
}

NR == 1 {
    next
}

{
    ann = $9

    # SnpEff can report several ANN records for one variant.
    # Historical parsing retained the first annotation.
    split(ann, annotations, ",")
    split(annotations[1], a, "|")

    print $1,
          $2,
          $3,
          $4,
          $5,
          $6,
          $7,
          $8,
          a[2],
          a[3],
          a[4],
          a[11],
          a[13],
          a[14],
          a[16]
}
' "${INPUT}" > "${OUTPUT}"


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

N_INPUT=$(( $(wc -l < "${INPUT}") - 1 ))
N_OUTPUT=$(( $(wc -l < "${OUTPUT}") - 1 ))

if [[ "${N_INPUT}" -ne "${N_OUTPUT}" ]]; then
    echo "[ERROR] Variant count changed during annotation parsing." >&2
    echo "[ERROR] Input variants:  ${N_INPUT}" >&2
    echo "[ERROR] Output variants: ${N_OUTPUT}" >&2
    exit 1
fi


echo
echo "============================================================"
echo "[SUCCESS] Variant table prepared successfully"
echo "============================================================"
echo
echo "[INFO] Variants:"
echo "       ${N_OUTPUT}"
echo
echo "[INFO] Output:"
echo "       ${OUTPUT}"